version: "3.4"
services:
  postgres:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=otis
      - POSTGRES_DB=test_database
      - POSTGRES_PASSWORD=password
